name: RiceQuaking
version: 1.01
main: top.ricequakes.ricequaking.RiceQuaking
api-version: 1.16

commands:
  sl:
    description: send your location
    usage: /<command>
  g:
    description: enable ghost mode
    usage: /<command>
  record:
    description: save location
    usage: /<command>
  r:
    description: save location
    usage: /<command>
  e:
    description: fast exchange items to ur ender chest
    usage: /<command>
  rm:
    description: open records gui
    usage: /<command>